### ISSUE TITLE
Tensorflow version

### ISSUE THREAD

**Issue by AmmarHasan** [Vaaceph/iris-flower-classification#1]
If you had to use Tensorflow 1/ core Api in classification.py , why did you installed Tensorflow 2 at first place and disable it at https://github.com/Vaaceph/iris-flower-classification/blob/a2c70396fcfaa87a42213354871e556edba931bc/classification.py#L4

**Comment by Vaaceph** [comment]
Yes, you are right.
This model is built on Tensorflow 1. So, related pip packages have been downgraded.
